# Health measuring devices settings. You can edit these.
# Terveysmittalaitteiden asetukset. Muokkaa tähän omat tietosi

[devices]
contour = 00:00:00:00:00:00
omron   = 00:00:00:00:00:00
beurer  = 00:00:00:00:00:00

[settings]
# Default output directory is health.py directory
# You can use year, month or day definition in file name
# Tallennushakemisto (oletus: ohjelman hakemisto)
# Tiedostonimen muoto — voit käyttää päivämäärämuuttujia:

#   {year}  = 2026
#   {month} = 05
#   {day}   = 25

# Examples:
#   healthmeasures.xlsx           (yksi tiedosto aina)
#   health_{year}-{month}.xlsx    (kuukausittainen tiedosto)
#   health_{year}.xlsx            (vuosittainen tiedosto)

directory = /home/user/Documents/Health/Measurements
filename = health_{year}.xlsx
